# Change these first
owner: 3mdeb # Your GitHub organization or username, where this repository lives
repo: upptime-site # The name of this repository

sites:
  - name: 3mdeb Website
    url: https://3mdeb.com
  - name: 3mdeb Shop
    url: https://shop.3mdeb.com/shop
  - name: 3mdeb Blog
    url: https://blog.3mdeb.com
  - name: 3mdeb Cloud
    url: https://cloud.3mdeb.com
  - name: 3mdeb Git
    url: https://git.3mdeb.com
  - name: 3mdeb Matrix Server
    url: https://matrix.3mdeb.com
  - name: 3mdeb Text Chat
    url: https://chat.3mdeb.com
  - name: 3mdeb Video Chat
    url: https://meet.3mdeb.com
  - name: 3mdeb Newsletter
    url: https://newsletter.3mdeb.com
  - name: Dasharo Documentation
    url: https://docs.dasharo.com
  - name: Dasharo Website
    url: https://dasharo.com
  - name: Dasharo Events
    url: https://vpub.dasharo.com
  - name: Dasharo Paste Service
    url: https://paste.dasharo.com/
  - name: Dasharo iPXE HTTP server
    url: https://boot.dasharo.com
  - name: Yocto cache for Dasharo Tools Suite (DTS)
    url: https://cache.dasharo.com
  - name: Fobnail Project Website
    url: https://fobnail.3mdeb.com
  - name: TwPM Project Website
    url: https://twpm.dasharo.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime-site
  logoUrl: https://cloud.3mdeb.com/index.php/s/zqdSdqZdbHf9zMd/download/Logo-White.svg
  name: Upptime
  introTitle: "Uptime status of websites managed by 3mdeb "
  introMessage: Uptime status of websites managed by 3mdeb
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
